<? /* Uj */ $kpfu_images_dir = $this->url('home') . "themes/mybootstrap3/images/kpfu_site/"; ?>
<div id="nav"  style="margin-bottom:10px;background-color:#444;background-image:url(<? /* Uj */ echo $kpfu_images_dir.'Group_7.png' ?>);color:white;font-size:14px;padding:14px 15px;font-family:Arial, sans-serif;">
<p align=center>
<!--table width="280" style="border-collapse: collapse;">
	<tr valign="top">
		<td width="80"><strong>Телефон:</strong></td>
		<td>(843) 264-47-34</td>
	</tr>
	<tr valign="top">
			<td width="80"><strong><nobr>E-mail:</nobr></strong></td>
			<td><a href="mailto:lsl@kpfu.ru">lsl@kpfu.ru</a></td>
	</tr>
	<tr valign="top">
			<td width="80"><strong>Адрес:</strong></td>
			<td>420008, Казань, ул.Кремлевская, д.35</td>
	</tr>
	</table-->
	Научная библиотека им. Н.И. Лобачевского <br>
	 420008, Казань, ул.Кремлевская, д.35, 
	 телефон: (843) 264-47-34, e-mail: lsl@kpfu.ru
	<!--nobr> <b>Телефон:</b>(843) 264-47-34</nobr><br>
	<nobr> <b>E-mail:</b>lsl@kpfu.ru</nobr><br>
	<nobr> <b>Адрес:</b>420008, Казань, ул.Кремлевская, д.35</nobr-->
 </p>
 </div>
<div class="clear"></div>