<br>
<div style="width:100%;margin-top:0px;margin-bottom:0px;padding-bottom:0px; overflow:hidden; margin: 0 auto; width: 60em; min-width: 960px; height: auto;">

	<table><tr><td>
	<? /* Uj */
        $kpfu_main_page  = "http://kpfu.ru/main_page";
        $kpfu_images_dir = $this->url('home') . "themes/mybootstrap3/images/kpfu_site/";
        ?>
	<a href="<? echo $kpfu_main_page ?>"><img src="<? echo $kpfu_images_dir.'Layer_157_1.gif' ?>" hspace="20" vspace="20"></img></a>
	</td>
	<td>
	<a  href="http://kpfu.ru/main_page" style="font-size: 18px; width: 100%; padding-top: 7px; font-family: Minion Pro,Times New Roman; color: rgb(0, 0, 0); font-weight: bold;text-decoration: none; "> 
		КАЗАНСКИЙ (ПРИВОЛЖСКИЙ) ФЕДЕРАЛЬНЫЙ УНИВЕРСИТЕТ </a>
    <br>
	<a  href="http://www.kpfu.ru/main_page?p_sub=5056" style="font-size: 18px; width: 90%; padding-top: 7px; font-family: Minion Pro,Times New Roman; color: rgb(0, 0, 0); font-weight: bold;text-decoration: none; display: block;"> 
		НАУЧНАЯ БИБЛИОТЕКА ИМ. Н.И. ЛОБАЧЕВСКОГО </a>
	</td></tr>
	</table>
</div>
<div class="clear"></div>
<div id="nav"  style="margin-bottom:10px;background-color:#444;background-image:url(<? /* Uj */ echo $kpfu_images_dir.'Group_7.png' ?>);color:white;font-size:14px;padding:14px 15px;font-family:Arial, sans-serif;">
<center>
    <a href="http://www.kpfu.ru/main_page?p_sub=8224" style="text-decoration: none;color:white">Сетевые ресурсы</a>&nbsp;&nbsp;
    <a href="http://www.kpfu.ru/main_page?p_sub=8474" style="text-decoration: none;color:white">Электронные каталоги</a>&nbsp;&nbsp;
    <a href="http://www.kpfu.ru/main_page?p_sub=8218" style="text-decoration: none;color:white">Цифровые коллекции</a>&nbsp;&nbsp;
    <a href="http://www.kpfu.ru/main_page?p_sub=8009" style="text-decoration: none;color:white">Вопрос библиографу</a>&nbsp;&nbsp;
	<!--a href="http://www.kpfu.ru/main_page?p_sub=8220" style="text-decoration: none;color:white">Читателям</a>&nbsp;
    <a href="http://www.kpfu.ru/main_page?p_sub=8221" style="text-decoration: none;color:white">О библиотеке</a>&nbsp;
    <a href="http://www.kpfu.ru/main_page?p_sub=12821" style="text-decoration: none;color:white">Образовательно-культурный комплекс</a>&nbsp;
    <a href="http://www.kpfu.ru/main_page?p_sub=8223" style="text-decoration: none;color:white">Наши партнеры</a>&nbsp;
    <a href="http://www.kpfu.ru/main_page?p_sub=17052" style="text-decoration: none;color:white">Интернет-приемная</a-->
 </center></div>
<div class="clear"></div>