<? $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType); ?>
<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
      <li<?=$tab['selected'] ? ' class="active"' : ''?>>

        <?                            /* Uj: popup text about search engine */
        $popup_title = "";
        switch (strtolower($tab['class'])):
          case ("solr"):
                $popup_title = $this->transEsc('Catalog_search_popup');
                break;
          case ("summon"):
                $popup_title = $this->transEsc('Summon_search_popup');
                break;
          case ("combined"):
                $popup_title = $this->transEsc('Combined_search_popup');
                break;
        endswitch;
        ?>

        <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' . ' title="' . $popup_title . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
      </li>
    <? endforeach; ?>
  </ul>
<? endif; ?>