<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
  <head>
    <?$this->headThemeResources()?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
      // Set global path for Javascript code:
      $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

      // Deal with cart stuff:
      if (!isset($this->renderingError)) {
        $cart = $this->cart();
        $this->jsTranslations()->addStrings(
          array(
            'bulk_email_success' => 'bulk_email_success',
            'bulk_save_success' => 'bulk_save_success',
            'close' => 'close',
            'loading' => 'Loading',
            'sms_success' => 'sms_success'
          )
        );
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/cookies.js");
          $this->headScript()->appendFile("cart.js");
          $this->jsTranslations()->addStrings(
            array(
              'bulk_noitems_advice' => 'bulk_noitems_advice',
              'confirmEmpty' => 'bookbag_confirm_empty',
              'viewBookBag' => 'View Book Bag',
              'addBookBag' => 'Add to Book Bag',
              'removeBookBag' => 'Remove from Book Bag',
              'itemsAddBag' => 'items_added_to_bookbag',
              'itemsInBag' => 'items_already_in_bookbag',
              'bookbagMax' => $cart->getMaxSize(),
              'bookbagFull' => 'bookbag_full_msg',
              'bookbagStatusFull' => 'bookbag_full',
            )
          );
        }
        $this->headScript()->appendScript($this->jsTranslations()->getScript());
      }

      // Session keep-alive
      if ($this->KeepAlive()) {
          $this->headScript()->appendScript('var keepAliveInterval = '
            . $this->KeepAlive());
          $this->headScript()->appendFile("keep_alive.js");
      }
    ?>
    <?=$this->headScript()?>

    <!-- IL: начало вставки для просмотрщика -->
    <!--script src="<?=$this->url('home')?>themes/mytheme/js/openseadragon.min.js"></script-->
      
        <script>
    $(function() {
      $( "#radio" ).buttonset();
    });
    </script>

    <script>
    $(function() {
      $( "#tabs" ).tabs();
    });
    </script>


    <style>
    .scroll-pane { overflow: auto; width: 100%; float:left; }
    .scroll-content { width: 2440px; float: left; }
    .scroll-content-item { width: 100px; height: 100px; float: left; margin: 10px; font-size: 1em; line-height: 96px; text-align: center; }
    .scroll-bar-wrap { clear: left; padding: 0 4px 0 2px; margin: 0 -1px -1px -1px; }
    .scroll-bar-wrap .ui-slider { background: none; border:0; height: 2em; margin: 0 auto;  }
    .scroll-bar-wrap .ui-handle-helper-parent { position: relative; width: 100%; height: 100%; margin: 0 auto; }
    .scroll-bar-wrap .ui-slider-handle { top:.2em; height: 1.5em; }
    .scroll-bar-wrap .ui-slider-handle .ui-icon { margin: -8px auto 0; position: relative; top: 50%; }
    </style>
    <script>
    $(function() {
      //scrollpane parts
      var scrollPane = $( ".scroll-pane" ),
        scrollContent = $( ".scroll-content" );
   
      //build slider
      var scrollbar = $( ".scroll-bar" ).slider({
        slide: function( event, ui ) {
          if ( scrollContent.width() > scrollPane.width() ) {
            scrollContent.css( "margin-left", Math.round(
              ui.value / 100 * ( scrollPane.width() - scrollContent.width() )
            ) + "px" );
          } else {
            scrollContent.css( "margin-left", 0 );
          }
        }
      });
   
      //append icon to handle
      var handleHelper = scrollbar.find( ".ui-slider-handle" )
      .mousedown(function() {
        scrollbar.width( handleHelper.width() );
      })
      .mouseup(function() {
        scrollbar.width( "100%" );
      })
      .append( "<span class='ui-icon ui-icon-grip-dotted-vertical'></span>" )
      .wrap( "<div class='ui-handle-helper-parent'></div>" ).parent();
   
      //change overflow to hidden now that slider handles the scrolling
      scrollPane.css( "overflow", "hidden" );
   
      //size scrollbar and handle proportionally to scroll distance
      function sizeScrollbar() {
        var remainder = scrollContent.width() - scrollPane.width();
        var proportion = remainder / scrollContent.width();
        var handleSize = scrollPane.width() - ( proportion * scrollPane.width() );
        scrollbar.find( ".ui-slider-handle" ).css({
          width: handleSize,
          "margin-left": -handleSize / 2
        });
        handleHelper.width( "" ).width( scrollbar.width() - handleSize );
      }
   
      //reset slider value based on scroll content position
      function resetValue() {
        var remainder = scrollPane.width() - scrollContent.width();
        var leftVal = scrollContent.css( "margin-left" ) === "auto" ? 0 :
          parseInt( scrollContent.css( "margin-left" ) );
        var percentage = Math.round( leftVal / remainder * 100 );
        scrollbar.slider( "value", percentage );
      }
   
      //if the slider is 100% and window gets larger, reveal content
      function reflowContent() {
          var showing = scrollContent.width() + parseInt( scrollContent.css( "margin-left" ), 10 );
          var gap = scrollPane.width() - showing;
          if ( gap > 0 ) {
            scrollContent.css( "margin-left", parseInt( scrollContent.css( "margin-left" ), 10 ) + gap );
          }
      }
   
      //change handle position on window resize
      $( window ).resize(function() {
        resetValue();
        sizeScrollbar();
        reflowContent();
      });
      //init scrollbar size
      setTimeout( sizeScrollbar, 10 );//safari wants a timeout
    });
    </script>
      
    <!-- IL: конец вставки -->	

  </head>
  <body>

    <!--IL/Uj: KFU-style top banner -->
     <div id="main_KFU">
    	<?=$this->render('top.phtml')?>
    </div>
    <div class="clear"></div>
    <!-- End of top banner -->

    <? // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
    <header role="banner" class="hidden-print">
      <div class="container navbar">
        <a class="sr-only" href="#content"><?=$this->transEsc('Skip to content') ?></a>
        <?=$this->render('header.phtml')?>
      </div>
      <div class="container">
        <nav class="nav searchbox hidden-lg hidden-print">
          <?=$this->layout()->searchbox ?>
        </nav>
        <? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
          && !empty($this->layout()->breadcrumbs)
          && $this->layout()->breadcrumbs !== false
        ): ?>
          <ul class="breadcrumb hidden-print">
          <? if(is_array($this->layout()->breadcrumbs)): ?>
            <? if(count($this->layout()->breadcrumbs) > 1): ?>
              <?=$this->render('breadcrumbs/multi.phtml', array(
                  'parents' => $this->layout()->breadcrumbs,
                  'title'   => $this->layout()->title,
                  'end'     => $this->layout()->breadcrumbEnd,
                  'from'    => $this->layout()->from
                )) ?>
            <? else: ?>
              <?=$this->render('breadcrumbs/default.phtml', array(
                  'parents' => $this->layout()->breadcrumbs,
                  'title'   => $this->layout()->title
                )) ?>
            <? endif; ?>
          <? else: ?>

            <? if (!isset($_GET["type"]) || strtolower($_GET["type"]) != "ids"): /*Uj*/ ?>
            <?=$this->layout()->breadcrumbs ?>
            <? endif; /* Uj (type "ids" is used for "technical" search) */ ?>

          <? endif; ?>
          </ul>
        <? endif; ?>
      </div>
    </header>
    <div role="main" class="main">
      <div class="container">
        <?=$this->layout()->content ?>
      </div>
    </div>
    <footer role="contentinfo" class="hidden-print">
      <div class="container">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy ?>
      </div>
    </footer>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="modalTitle" class="modal-title"></h4>
          </div>
          <div class="modal-body"><?=$this->transEsc('Loading') ?>...</div>
        </div>
      </div>
    </div>
 
    <!-- IL/Uj: KFU-style bottom banner -->
      <div id="main_KFU_new">
    	<?=$this->render('bottom.phtml')?>
    </div>
    <div class="clear"></div>
    <!-- End of bottom banner -->

    <?=$this->googleanalytics()?>
    <?=$this->piwik()?>
  </body>
</html>
